### ISSUE TITLE
KPCA: projection of arbitrary vector after kpca is done

### ISSUE THREAD

**Issue by stenczelt** [BingqingCheng/ASAP#15]
After performing KPCA on a given kernel matrix, then an arbitrary vector can be projected to the same embedding.

This requires:
- kernel needs to be computed between the vector of interest and the original points (preservation of the original vectors)
- centering: only the column means (and the mean of this to be added back) as in `asaplib.pca.fixcenter()`
- projection vectors

I am using such projections at the moment, in code written separately because of the lack of functionality here, but I am happy to implement something like this here.

I can see that this would work the best with a KPCA class, rather than a function, to store the needed arrays and have all the methods to perform the above operations. This suggests changing the current code, or perhaps just making a class that is wrapped by a simple function that carries out the current functionality of `asaplib.pca.kpca(kNN, kpca_d)`. 

What do you think @BingqingCheng and @Ryan-Rhys?

**Comment by BingqingCheng** [comment]
Yes, I agree that having such functionalities for projecting atomic environment in KPCA is good. I also think that having a class makes sense and makes the method for extensible.

**Comment by Ryan-Rhys** [comment]
Not too familiar with this area of the codebase but more than happy to learn about it and review a PR!

**Comment by stenczelt** [comment]
I am working in it atm in a new branch!

**Comment by stenczelt** [comment]
class and unittest added, see: d89fe8bd8921b486cca4d74690c9fac72e952fe0

Actually, having unittests for things in general would not be out of place at all, I have tarted the framework for them now.

**Comment by stenczelt** [comment]
Only the implementation of using the explicit vectors is needed
