### ISSUE TITLE
clustering.py doesn't work

### ISSUE THREAD

**Issue by BingqingCheng** [BingqingCheng/ASAP#23]
clustering.py needs serious clean-up. Besides, the clustering example in TiO2 doesn't work.

@Ryan-Rhys

**Comment by Ryan-Rhys** [comment]
I can look into this. Is the TiO2 error the same one I referenced before or a different one?

**Comment by Ryan-Rhys** [comment]
Namely:

`RuntimeError: KDE did not work. Try smaller dimension.`

when clustering.py is executed in the final step of the example.

**Comment by BingqingCheng** [comment]
For me, first of all the syntax doesn't work (the -fxyz flag). We should add the asapxyz parser.

Then when you use -d 4 so whatever the kde is okay, but the clustering result looks weird.
