### ISSUE TITLE
How do I add new dependencies to the continuous integration build?

### ISSUE THREAD

**Issue by Ryan-Rhys** [BingqingCheng/ASAP#35]
I'm not sure who implemented this @zhubonan ? 

I'm looking to add an RDKit dependency (which seems to be used in both the photoswitch and QM9 visualisation examples now) to the continuous integration build. As far as I can see the build is running `setup.py` and we have `install_requires` and `extras_require` keyword args. Any idea where RDKit should go?

**Comment by zhubonan** [comment]
My guess is that if it is just used for testing it can probably be just added to the CI script. 

You can add any commands for its installation here:

https://github.com/BingqingCheng/ASAP/blob/ec3986b6151eab05cd4ca0047048b59acac37347/.github/workflows/pythonpackage.yml#L22-L26

But a quick google seems to suggest it needs conda? Then we probably have to setup a conda environment using the github action here:
https://github.com/marketplace/actions/setup-conda

**Comment by Ryan-Rhys** [comment]
Thanks for that Bonan! Tests are passing now

**Comment by zhubonan** [comment]
I guess it is sorted? Closing the issue...
