### ISSUE TITLE
no apparent way to control SOAP hypers in asap command, and defaults aren't great

### ISSUE THREAD

**Issue by bernstei** [BingqingCheng/ASAP#36]
Is there's a way to control SOAP parameters in the command line interface? I'm trying on a pure Li system, and `asap gen_desc -f configs.extxyz soap` has decided to use n/lmax 6,6 and cutoff=3. For one, we're converging to the opinion that nmax should be larger than lmax (12,3 rather than 6,6), and cutoff 3.0 is definitely too short for Li. `asap gen_desc -h` doesn't indicate any way to control the SOAP settings.  It would also be nice to use the universal multi-SOAPs as well.

**Comment by BingqingCheng** [comment]
Hello, one needs

Asap gen_desc soap —help to get the help string

For universal soaps

asap gen_desc soap -u smart or minimal or longrange

**Comment by bernstei** [comment]
Thanks.  I thought I checked that, but apparently not.  Aah - I may have only tried "-h", not "--help".

**Comment by bernstei** [comment]
What does "--crossover" do?

**Comment by BingqingCheng** [comment]
It’s the cross terms between different species when computing the power
spectra

**Comment by gabor1** [comment]
And does it default to on or off?

-- Gábor

**Comment by BingqingCheng** [comment]
Off

**Comment by bernstei** [comment]
I would suggest a more descriptive name, maybe "--multispecies_crossterms" ?  Also, I think it should default to on.

							Noam


____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by BingqingCheng** [comment]
I changed the default behavior to use "minimal" universal soap.

Re crossover, it should adds info, but in practice I don't really see the improvement in visualization.
