### ISSUE TITLE
parallelise descriptor computation. 

### ISSUE THREAD

**Issue by zhubonan** [BingqingCheng/ASAP#39]
It would be nice to use all those core of a PC. 

At the moment ASAP is serial. It would be relatively easy to parallelise over the frames using `multiprocessing.Pool` in the following code: 

https://github.com/BingqingCheng/ASAP/blob/2ccd2984f61b884cdc7290f45f6c61c98ef8ffa0/asaplib/data/xyz.py#L197-L205

There can be some complications while combining this with having a progress bar, but solutions can be found at https://github.com/tqdm/tqdm/issues/484. 
 
Alternatively, there is already parallel implementation in `dscribe`, but one needs to modify the call stack and group the calls to `SOAP.create` together.

**Comment by BingqingCheng** [comment]
I prefer to do this at the asap level, as not all descriptors are parallelized, and this is really a trivial parrallelzation.

To do this properly, I'm thinking perhaps we first sort the frames according to sizes (as a proxy to the associated computing cost), and then start N processes for each N frames with similar sizes.

What do you think?

**Comment by zhubonan** [comment]
I agree. Sorting is probably not necessary as one can just strip the input frames? There might be some complications for avoiding using too much memory. For example, if the child process just inherent all the resources, the memory cost will increase N fold.  

It may be better to use the `joblib` library, this is what `dscribe` uses. 

https://joblib.readthedocs.io/en/latest/parallel.html#embarrassingly-parallel-for-loops

**Comment by BingqingCheng** [comment]
done
