### ISSUE TITLE
DScribe now supports coherent averaging

### ISSUE THREAD

**Issue by gabor1** [BingqingCheng/ASAP#45]
This is not really an "issue" of ASAP, just a note to point out that following my suggestion, DScribe have now implemented the "coherent average" option, which allows you to compute a descriptor for an entire structure by averaging the Ylm coefficients before squaring them to get the soap vector. The corresponding DScribe option is `average="inner"` . It might be interesting to propagate this option to ASAP too in some way (not necessarily using the same keyword).

**Comment by BingqingCheng** [comment]
It's very annoying; they changed the syntax of their functions, and also the output when you don't do any averaging!

**Comment by gabor1** [comment]
you could try to comment them highlighting how important it is to not change syntax unless they REALLY REALLY have to..

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by BingqingCheng** [comment]
This is now added
