### ISSUE TITLE
clingo not available on CentOS 7 or OS X

### ISSUE THREAD

**Issue by bernstei** [BingqingCheng/ASAP#50]
The asap command line, when doing something as simple as `asap gen_desc -h` seems to look for clingo, which is apparently not findable either for CentOS 7 or OS X (macports python).
```
> asap gen_desc -h
W:      asap: 72:Could not find clingo python module in global or local (~/.asap/) installation
D:buildclingo.py:149:got LSB id CentOS and release 7.8.2003
I:buildclingo.py:184:installing for untested Linux id 'CentOS' and release '7.8.2003' (tested = Ubuntu ['16.04', '16.10', '17.04'] and Debian ['?'])
I:buildclingo.py: 57:obtaining list of installed packages with command ['dpkg-query', '-W', '-f=${Package}\\n']
C:buildclingo.py:188:We are sorry, could not determine your operating system. Please contact the developers.
C:      asap: 75:Could not install clingo python module. Please retry or install manually and retry running asap.
```
What is this module, and why is it so hard to install?

**Comment by BingqingCheng** [comment]
Hello,

We don't use the clingo, at least not in my knowledge. I searched this package on my laptop and it is not installed either.

When you do `import asaplib` in python3, does it work?

If you use a fresh conda env to install asap, does it work?

**Comment by bernstei** [comment]
Sorry, my mistake - while poking around trying to remind myself how to update asap, I must have done "pip install --upgrade asap", which is some completely different software with the same name.
