### ISSUE TITLE
reproduce example from documentation

### ISSUE THREAD

**Issue by lydiash** [BingqingCheng/ASAP#59]
Hello, in your documentation you have a demonstration of how to use asaplib (https://bingqingcheng.github.io/howto_asaplib.html), but I can't find the file 'P-20GPa/result-complete/combined.xyz' or 'P-20GPa/result-complete/ranking-complete' to make the same picture. Are they available for public use?

**Comment by BingqingCheng** [comment]
Hello. Sorry that I didn't put these in the current repo, but if you are interested, you can find the files at
https://github.com/BingqingCheng/Mapping-the-space-of-materials-and-molecules/tree/master/TiO2
