### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'rcut'

### ISSUE THREAD

**Issue by sumanbhasker89** [BingqingCheng/ASAP#61]
(A very trivial question)
I am trying out the soap descriptor generation on small_molecules-1000.xyz in ./tests/.  The command below:
"asap gen_desc -f small_molecules-1000.xyz soap"
gives a Type error:
"TypeError: __init__() got an unexpected keyword argument 'rcut'"
Not sure what I am missing? Could you please help.

Thanks,

**Comment by link89** [comment]
You have to downgrade the `describe` package to 1.x.x version, for example 
```bash
pip install dscribe==1.2.2
```

**Comment by sumanbhasker89** [comment]
That works! Thank you.
