### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by Ryan-Rhys** [BingqingCheng/ASAP#8]
### Working Examples

1. B-RSS-train-set
2. revpbe0-water-train-set
3. Tungstun-train-set (Tungsten?)

### Broken Examples

1. Ni-icosahedral-np
2. TiO2-RSS

Fail with the error:

`File "/Users/Ryan-Rhys/ml_physics/asap/ASAP/asap/asaplib/kde/ml_density_estimation.py", line 164, in find_optimal_bandwidth
    assert abs(h_optimal - hmin) > 1e-4, "Lower boundary reached for bandwidth"
AssertionError: Lower boundary reached for bandwidth`

3. Lennard-Jones-nucleus
4. ice-phases

Fail with the error:

`File "../../asap/pca.py", line 202, in <module>
    main(args.fmat, args.fxyz, args.tags, args.colors, args.colorscolumn, args.prefix, args.output, args.peratom, args.keepraw, args.scale, args.d, args.pc1, args.pc2, args.plotatomic, args.adjusttext)
  File "../../asap/pca.py", line 66, in main
    if len(desc)==0: raise ValueError('Please supply descriptor in a xyz file or a standlone descriptor matrix')`

5. single-triplet-fission

Fails with the error:

`frame_select.py: error: unrecognized arguments: -n 1000`

6. water-nnp-trainset

has no README file.

**Comment by Ryan-Rhys** [comment]
1. water-npp-trainset example is missing a README file.
2. small molecules example is now broken following the change to the way soap hyperparameters are generated.
3. TiO2 example currently fails with a bandwidth estimation error in the kernel density estimation routine. This error occurs even using just single dimension.

All other examples working as expected.

**Comment by zhubonan** [comment]
For me (on b61e883f0083a) the TiO2-RSS example fails with this error:
```python
Traceback (most recent call last):
  File "/home/bonan/miniconda3/envs/asap/bin/pca.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bonan/appdir/ASAP/scripts/pca.py", line 190, in <module>
    main(args.fmat, args.fxyz, args.tags, args.colors, args.colorscolumn, args.prefix, args.output, args.peratom,
  File "/home/bonan/appdir/ASAP/scripts/pca.py", line 94, in main
    plotcolor, colorlabel, colorscale = set_color_function(fcolor, asapxyz, colorscol, len(proj), False)
  File "/home/bonan/appdir/ASAP/asaplib/plot/plot_colors.py", line 18, in set_color_function
    if os.path.isfile(fcolor):
  File "/home/bonan/miniconda3/envs/asap/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

https://github.com/BingqingCheng/ASAP/blob/fab3abef40959389dc647275affa4191734233e7/asaplib/plot/plot_colors.py#L70-L75

change `if os.path.isfile(fcolor):` to `if fcolor and os.path.isfile(fcolor):` solves the problem.

But there is another exception raised when saving the plot:
```python
  File "/home/bonan/miniconda3/envs/asap/bin/pca.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bonan/appdir/ASAP/scripts/pca.py", line 190, in <module>
    main(args.fmat, args.fxyz, args.tags, args.colors, args.colorscolumn, args.prefix, args.output, args.peratom,
  File "/home/bonan/appdir/ASAP/scripts/pca.py", line 154, in main
    fig.savefig('PCA_4_' + prefix + '-c-' + fcolor + '.png')
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by BingqingCheng** [comment]
@zhubonan  Now it's fixed. The error was because the color function was not set. Now I set the default to using index of samples.

**Comment by BingqingCheng** [comment]
I think all the examples @Ryan-Rhys mentioned are working okay now
